name: openwallabydotcom

services:
  webserver:
    image: joseluisq/static-web-server:2-alpine
    container_name: "webserver"
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    environment:
      - SERVER_ROOT=/var/public
      - SERVER_CONFIG_FILE=/etc/config.toml
    volumes:
      - ./public:/var/public
      - ./config/sws.toml:/etc/config.toml
      - /etc/letsencrypt/live/openwallaby.com/fullchain.pem:/etc/certs/fullchain.pem
      - /etc/letsencrypt/live/openwallaby.com/privkey.pem:/etc/certs/privkey.pem